#!/bin/bash

# BUILD SCRIPT FOR RUST BEVY PROGRAM
# THE POINT OF THIS SCRIPT IS TO MAKE IT EASY TO COMPILE AND COPY THE ASSETS FOLDER AND ZIP IT AUTOMATICALLY
# THIS SCRIPT IS NOT REQUIRED TO BUILD THE PROGRAM, IT IS JUST A CONVENIENCE SCRIPT

PROJECT_NAME=flappy-bevy
BUILD_DIR=build
ASSETS_DIR=assets
ZIP_FILE=$BUILD_DIR/$PROJECT_NAME.zip

if [ ! -d "$BUILD_DIR" ]; then
  mkdir $BUILD_DIR
fi

cargo build --release

cp -R $ASSETS_DIR $BUILD_DIR/$ASSETS_DIR

cp target/release/$PROJECT_NAME $BUILD_DIR

# Compress the build directory into a zip file in the main directory
cd $BUILD_DIR
zip -r ../$PROJECT_NAME.zip *
cd ..

rm -rf $BUILD_DIR